# ----- training hyper-parameters -----
seed:        3407
device:      cuda          # "cuda" | "cpu"
epochs:      100
batch_size:  128
lr:          1.0e-3
weight_decay: 1.0e-2
ema_decay:   0.995
scheduler:
  T_max: 10000
  eta_min: 1e-5

# ----- diffusion process -----
T:           1000          # total timesteps
time_dim:    128
beta_schedule: cosine

# ----- paths -----
data_root:   "./data/mnist"
output_root: "./outputs"
